// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObsProject.Models;

#nullable disable

namespace ObsProject.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221019183712_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ObsProject.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Hobbys")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");
                });

            modelBuilder.Entity("ObsProject.Models.İlceler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("ilceadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sehirid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("sehirid");

                    b.ToTable("İlcelers");
                });

            modelBuilder.Entity("ObsProject.Models.İller", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("sehiradi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("İllers");
                });

            modelBuilder.Entity("ObsProject.Models.StudentHobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HobbyId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentHobbies");
                });

            modelBuilder.Entity("ObsProject.Models.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Grup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ObsProject.Models.Teachers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ObsProject.Models.TeacherStudens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClasssTeacherId")
                        .HasColumnType("int");

                    b.Property<int>("GuideTeacherId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClasssTeacherId");

                    b.HasIndex("GuideTeacherId");

                    b.HasIndex("StudentId");

                    b.ToTable("TeacherStudens");
                });

            modelBuilder.Entity("ObsProject.Models.İlceler", b =>
                {
                    b.HasOne("ObsProject.Models.İller", "İller")
                        .WithMany("İlcelers")
                        .HasForeignKey("sehirid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("İller");
                });

            modelBuilder.Entity("ObsProject.Models.StudentHobby", b =>
                {
                    b.HasOne("ObsProject.Models.Hobby", "Hobby")
                        .WithMany("StudentHobbies")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObsProject.Models.Students", "Students")
                        .WithMany("StudentHobbies")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobby");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("ObsProject.Models.Students", b =>
                {
                    b.HasOne("ObsProject.Models.İlceler", "İlcelers")
                        .WithMany("Students")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("İlcelers");
                });

            modelBuilder.Entity("ObsProject.Models.TeacherStudens", b =>
                {
                    b.HasOne("ObsProject.Models.Teachers", "ClassTeachers")
                        .WithMany("TeacherStudens")
                        .HasForeignKey("ClasssTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObsProject.Models.Teachers", "GuideTeachers")
                        .WithMany("TeacherStudensGuide")
                        .HasForeignKey("GuideTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObsProject.Models.Students", "Students")
                        .WithMany("TeacherStudens")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassTeachers");

                    b.Navigation("GuideTeachers");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("ObsProject.Models.Hobby", b =>
                {
                    b.Navigation("StudentHobbies");
                });

            modelBuilder.Entity("ObsProject.Models.İlceler", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ObsProject.Models.İller", b =>
                {
                    b.Navigation("İlcelers");
                });

            modelBuilder.Entity("ObsProject.Models.Students", b =>
                {
                    b.Navigation("StudentHobbies");

                    b.Navigation("TeacherStudens");
                });

            modelBuilder.Entity("ObsProject.Models.Teachers", b =>
                {
                    b.Navigation("TeacherStudens");

                    b.Navigation("TeacherStudensGuide");
                });
#pragma warning restore 612, 618
        }
    }
}
